# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitVersionNext < Formula
  desc "increments version (git tag) numbers simply"
  homepage "https://github.com/kazeburo/git-version-next"
  version "0.0.5"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/kazeburo/git-version-next/releases/download/v0.0.5/git-version-next_darwin_amd64.zip"
    sha256 "f3520f6a760f2a89348e0d6ee7f8ba7d4f7169b34893639f1188e88bb6ef65e1"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/kazeburo/git-version-next/releases/download/v0.0.5/git-version-next_darwin_arm64.zip"
    sha256 "fa77786104e7c3ba3108c0ba774fa831dd31fdda0b897eda46e9c349c6df83eb"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/kazeburo/git-version-next/releases/download/v0.0.5/git-version-next_linux_amd64.zip"
    sha256 "0399891033f1ba394726b08fcb5fa2be5c31529bba9942dc4add8d808d905015"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/kazeburo/git-version-next/releases/download/v0.0.5/git-version-next_linux_arm64.zip"
    sha256 "cd5707e782984f25b0882985bd92d07f144970fd23c42d668845fb3f5f87fac2"
  end

  def install
    bin.install "git-version-next"
  end
end
