# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitVersionNext < Formula
  desc "increments version (git tag) numbers simply"
  homepage "https://github.com/kazeburo/git-version-next"
  version "0.0.6"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kazeburo/git-version-next/releases/download/v0.0.6/git-version-next_darwin_arm64.zip"
      sha256 "3c4e74f5f6322cfb75a2d2ffb461a37620e098f14b337613ce55364d7ed3b532"

      def install
        bin.install "git-version-next"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kazeburo/git-version-next/releases/download/v0.0.6/git-version-next_darwin_amd64.zip"
      sha256 "5248fbb54a6d5371fc29dcf39c1c9cd27dc2e19f912c3193c2bca1f46b48f1b9"

      def install
        bin.install "git-version-next"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kazeburo/git-version-next/releases/download/v0.0.6/git-version-next_linux_amd64.zip"
      sha256 "c4936be7be5721f1dce34da5e04517dcf708dfc9949e1eb81e5b5ededdd43346"

      def install
        bin.install "git-version-next"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kazeburo/git-version-next/releases/download/v0.0.6/git-version-next_linux_arm64.zip"
      sha256 "b1c20557d3b42c2028d7eaeda356187ed0dbc06f84326ff36223ad342858d2ba"

      def install
        bin.install "git-version-next"
      end
    end
  end
end
