# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sacloudns < Formula
  desc "increments version (git tag) numbers simply"
  homepage "https://github.com/kazeburo/sacloudns"
  version "0.0.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kazeburo/sacloudns/releases/download/v0.0.8/sacloudns_darwin_amd64.zip"
      sha256 "c0c4af615fb94717167dca03559110ec5e4da52a08417df6f88993fec6f29255"

      define_method(:install) do
        bin.install "sacloudns"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kazeburo/sacloudns/releases/download/v0.0.8/sacloudns_darwin_arm64.zip"
      sha256 "216d7cbcb6fd06ccf4030e3bd368fd072fa410098d6b47ec397af6a638738e16"

      define_method(:install) do
        bin.install "sacloudns"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kazeburo/sacloudns/releases/download/v0.0.8/sacloudns_linux_amd64.zip"
      sha256 "7bae77ec494283a3f0e9004f3b76214ae4ceceb3c4d17039a2a411112c44c334"
      define_method(:install) do
        bin.install "sacloudns"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kazeburo/sacloudns/releases/download/v0.0.8/sacloudns_linux_arm64.zip"
      sha256 "0876c60803341487dd2f09224364324bc9681aa3a863e92d342c29fd834131d0"
      define_method(:install) do
        bin.install "sacloudns"
      end
    end
  end
end
