# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sacloudns < Formula
  desc "increments version (git tag) numbers simply"
  homepage "https://github.com/kazeburo/sacloudns"
  version "0.0.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kazeburo/sacloudns/releases/download/v0.0.9/sacloudns_darwin_amd64.zip"
      sha256 "33ae54d3b3e6594dc36406edf6371d9c5bbceb383d1335fd8ceb75cf2eb396e2"

      define_method(:install) do
        bin.install "sacloudns"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kazeburo/sacloudns/releases/download/v0.0.9/sacloudns_darwin_arm64.zip"
      sha256 "2d2655c741afba5c8492a4f7190f5de4f9bc8f1847d477dbacd136dc69c72255"

      define_method(:install) do
        bin.install "sacloudns"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kazeburo/sacloudns/releases/download/v0.0.9/sacloudns_linux_amd64.zip"
      sha256 "68b726bcaf5dd6adfbe8859c7c803b79049362c7b8d09b1c040846611513e5e2"
      define_method(:install) do
        bin.install "sacloudns"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kazeburo/sacloudns/releases/download/v0.0.9/sacloudns_linux_arm64.zip"
      sha256 "f73e06688397954740bb037b08529d7d52a453f247c65708310923258cae98e2"
      define_method(:install) do
        bin.install "sacloudns"
      end
    end
  end
end
